export default {
  'header.homeTitle': 'Home',
  'header.homeUrl': '',
  'header.myJobsDBTitle': 'MyJobsDB',
  'header.myJobsDBUrl': '/MyJobsDB',
  'header.resourcesTitle': 'Resources',
  'header.resourcesUrl': '/en-hk/career-recruitment-advice/',
  'header.careerInsightsTitle': 'Career Insights',
  'header.careerInsightsUrl': '/career-insights',
  'header.myAccountTitle': 'My Account',
  'header.myAccountUrl': '/MyJobsDB',
  'header.employerSiteTitle': 'Employer Site',
  'header.employerLinkPrefix': 'Looking to hire? Check out our ',
  'header.employerSiteUrl': '/Home/EmployerIndex',
  'header.loginTitle': 'Log in',
  'header.loginUrl': 'https://hk.v8.dev.jobsdb.com/hk/en/login/jobseekerlogin?from=header#start',
  'header.signupTitle': 'Sign up',
  'header.signupUrl': '/jobseeker/registration',
  'header.profileTitle': 'View profile',
  'header.profileUrl': 'https://hk.v8.preview.jobsdb.com/hk/en/MyJobsDB/profile',
  'header.invitationTitle': 'No job invitations',
  'header.invitationUrl': '/Invitations/InvitationList',
  'header.logoutTitle': 'Log Out',
  'header.logoutUrl': 'https://www.thisislogoutlink.test',
  'menu.jobSeekerHeader': 'JOB SEEKER',
  'menu.settingsHeader': 'SETTINGS',
  'menu.more': 'More',
  'menu.moreHeader': 'MORE',
  'menu.countryAndLanguage': 'Country & Language',
  'menu.backToMenu': 'Back to Menu'
};
