version: 2

groups:
  reviewers:
    required: 2
    teams:
      - seek-style-guide-contributors
      - front-end-contributors
    # Enable github reviews when integration is sufficient:
    # https://github.com/pullapprove/support/issues/98#issuecomment-256447253
    # github_reviews:
    #   enabled: true
    approve_by_comment:
      enabled: false
    always_rejected:
      title_regex: '^(?!(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?\:\s(\S+)).*$'
      explanation: 'Invalid title. Please read the contribution guide: https://github.com/seek-oss/seek-style-guide/blob/master/CONTRIBUTING.md'
    reset_on_push:
      enabled: false
    reset_on_reopened:
      enabled: true
