language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST_SHA" ]; then
      npm run deploy-surge -- -d seek-style-guide--${TRAVIS_PULL_REQUEST_SHA}.surge.sh;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      npm run semantic-release;

      git config --global user.name "Travis-CI";
      git config --global user.email "travis@example.com";
      npm run build-gh-pages;
      npm run deploy-gh-pages;
    fi
