export default {
  'footer.copyright': 'Copyright © 1998-{year}, jobsDB.',
  'footer.rightReserved': 'All Rights Reserved.',
  'footer.siteMapLink': '/hk/en/sitemap',
  'footer.siteMapLinkText': 'Site Map',
  'footer.termsLink': '/en-hk/pages/terms/terms-conditions',
  'footer.termsLinkText': 'Terms & Conditions',
  'footer.privacyLink': '/en-hk/pages/terms/privacy-policy',
  'footer.privacyLinkText': 'Privacy Statement',

  'footer.csemailtext': 'Email: ',
  'footer.csemail': 'CS@jobsDB.com',
  'footer.csemailLink': 'mailto:CS@jobsDB.com',
  'footer.cshotline':'+852 2332 8832',
  'footer.officehour':'(Mon - Fri, 9am - 6pm)',
  'footer.jobpostingenquiry':'Job Posting Enquiry:',
  
  'footer.jobseekers':'Job Seekers',
  'footer.browsejobs':'Browse Jobs',
  'footer.browsejobsLink': '/hk/en/browse',
  'footer.postresumes':'Post Resumes',
  'footer.postresumesLink': '/hk/en/Resumes/ResumeIndex',
  'footer.jobalerts':'Job Alerts',
  'footer.jobalertsLink': '/hk/en/JobAlert/JobAlertCreation',
  'footer.myjobsdb':'My jobsDB',
  'footer.myjobsdbLink': '/hk/en/MyJobsDB',
  'footer.careerinsights':'Career Insights',
  'footer.careerinsightsLink':'/hk/en/career-insights',

  'footer.employers':'Employers',
  'footer.postajob':'Post a Job',
  'footer.postajobLink':'/hk/en/Home/EmployerIndex',
  'footer.searchcandidates':'Search Candidates',
  'footer.searchcandidatesLink':'/hk/en/StaticContentFullContainer/EM/FindTalent.htm',
  'footer.advertisewithus':'Advertise with us',
  'footer.advertisewithusLink':'/hk/en/StaticContent/AboutUs/Products.htm',

  'footer.aboutus':'About Us',
  'footer.aboutjobsdb':'About jobsDB',
  'footer.aboutjobsdbLink':'/en-hk/pages/aboutus',
  'footer.faq':'FAQ',
  'footer.faqLink':'/hk/en/StaticContentFullContainer/AboutUS/faq/index.htm',
  'footer.careenatjobsdb':'Career@jobsDB',
  'footer.careenatjobsdbLink':'/hk/en/Search/FindJobs?JSRV=1&AccNums=1&SubAccount=14',
  'footer.contactus':'Contact Us',
  'footer.contactusLink':'/en-hk/pages/regional-coverage',

  'footer.tools':'Tools',
  'footer.mobileversion':'Mobile Version',
  'footer.mobileversionLink':'/en-hk',
  'footer.rss':'RSS',
  'footer.rssLink':'/hk/en/Rss/RenderJobFunctionRssIndex',

  'footer.internationalpartners':'International Partners',
  'footer.babajobindia':'BabaJob (India)',
  'footer.babajobindiaLink':'http://www.babajob.com/',
  'footer.bdjobsbandladesh':'Bdjobs (Bandladesh)',
  'footer.bdjobsbandladeshLink':'http://www.bdjobs.com/',
  'footer.brightermondayeastafrica':'Brighter Monday (East Africa)',
  'footer.brightermondayeastafricaLink':'http://www.brightermonday.com/',
  'footer.cathobrazil':'Catho (Brazil)',
  'footer.cathobrazilLink':'http://www.catho.com.br/',
  'footer.jobbermanwestafrica':'Jobberman (West Africa)',
  'footer.jobbermanwestafricaLink':'http://www.jobberman.com/',
  'footer.jobstreetseasia':'JobStreet (S.E. Asia)',
  'footer.jobstreetseasiaLink':'http://www.jobstreet.com/',
  'footer.jorahongkong':'Jora (Hong Kong)',
  'footer.jorahongkongLink':'https://hk.jora.com/',
  'footer.managerbrazil':'Manager (Brazil)',
  'footer.managerbrazilLink':'http://www.manager.com.br/',
  'footer.occmundialmexico':'OCC Mundial (Mexico)',
  'footer.dccmundialmexicoLink':'https://www.occ.com.mx/',
  'footer.seamanjobsitephilippines':'Seaman Jobsite (Philippines)',
  'footer.seamanjobsitephilippinesLink':'http://www.seamanjobsite.com/',
  'footer.seekaustralia':'SEEK (Australia)',
  'footer.seekaustraliaLink':'http://www.seek.com.au/',
  'footer.workabroadphilippines':'Work Abroad (Philippines)',
  'footer.workabroadphilippinesLink':'http://www.workabroad.ph/',
  'footer.workana':'Workana',
  'footer.workanaLink':'https://www.workana.com/',
  'footer.zhaopinchina':'Zhaopin (China)',
  'footer.zhaopinchinaLink':'http://www.zhaopin.com/',

  'footer.facebookLink':'http://www.facebook.com/jobsDB.HongKong',
  'footer.googleplusLink':'https://plus.google.com/+jobsdbHK',
  'footer.weiboLink':'http://weibo.com/jobsdbhk',
  'footer.twitterLink':'http://twitter.com/HKJobs',
  'footer.rssLink':'http://hk.jobsdb.com/HK/EN/Rss/RenderJobFunctionRssIndex'
};
