
export default {
  'footer.copyright': 'Copyright © 1998-{year}, jobsDB. ',
  'footer.rightReserved': 'All Rights Reserved.',
  'footer.siteMapLink': '/id/en/sitemap',
  'footer.siteMapLinkText': 'Site Map',
  'footer.termsLink': '/en-id/pages/terms/terms-conditions',
  'footer.termsLinkText': 'Terms & Conditions',
  'footer.privacyLink': '/en-id/pages/terms/privacy-policy',
  'footer.privacyLinkText': 'Privacy Statement',

  'footer.csemailtext': 'Email: ',
  'footer.csemail': 'CS@jobsDB.co.id',
  'footer.csemailLink': 'mailto:CS@jobsDB.co.id',
  'footer.cshotline':'Phone: +62 21 3002 8899 ',
  'footer.csFax':'Fax: +62 21 3002 8888 / +62 21 5795 7733',
  'footer.officehour':'(Mon - Fri, 8:00am - 5:00pm)',
  'footer.jobpostingenquiry':'Job Posting Enquiry:',
  
  'footer.jobseekers':'Job Seekers',
  'footer.browsejobs':'Browse Jobs',
  'footer.browsejobsLink': '/id/en/browse',
  'footer.postresumes':'Post Resumes',
  'footer.postresumesLink': '/id/en/Resumes/ResumeIndex',
  'footer.jobalerts':'Job Alerts',
  'footer.jobalertsLink': '/id/en/JobAlert/JobAlertCreation',
  'footer.myjobsdb':'My jobsDB',
  'footer.myjobsdbLink': '/id/en/MyJobsDB',

  'footer.employers':'Employers',
  'footer.postajob':'Post a Job',
  'footer.postajobLink':'/id/en/Home/EmployerIndex',
  'footer.searchcandidates':'Search Candidates',
  'footer.searchcandidatesLink':'/ID/en/StaticContentFullContainer/EM/FindTalent.htm',
  'footer.advertisewithus':'Advertise with Us',
  'footer.advertisewithusLink':'/en-id/pages/products-services',

  'footer.aboutus':'About Us',
  'footer.aboutjobsdb':'About jobsDB',
  'footer.aboutjobsdbLink':'/en-id/pages/aboutus',
  'footer.faq':'FAQ',
  'footer.faqLink':'/id/en/StaticContentFullContainer/AboutUS/faq/index.htm',
  'footer.careenatjobsdb':'Career@jobsDB',
  'footer.careenatjobsdbLink':'/ID/en/Search/FindJobs?PN=JobListing&Companies=%22jobsDB%22',
  'footer.contactus':'Contact Us',
  'footer.contactusLink':'/en-id/pages/regional-coverage',

  'footer.tools':'Tools',
  'footer.mobileversion':'Mobile Version',
  'footer.mobileversionLink':'/en-id',
  'footer.rss':'RSS',
  'footer.rssLink':'/id/en/Rss/RenderJobFunctionRssIndex',

  'footer.internationalpartners':'International Partners',
  'footer.babajobindia':'BabaJob (India)',
  'footer.babajobindiaLink':'http://www.babajob.com/',
  'footer.bdjobsbandladesh':'Bdjobs (Bangladesh)',
  'footer.bdjobsbandladeshLink':'http://www.bdjobs.com/',
  'footer.brightermondayeastafrica':'Brighter Monday (East Africa)',
  'footer.brightermondayeastafricaLink':'http://www.brightermonday.com/',
  'footer.cathobrazil':'Catho (Brazil)',
  'footer.cathobrazilLink':'http://www.catho.com.br/',
  'footer.jobbermanwestafrica':'Jobberman (West Africa)',
  'footer.jobbermanwestafricaLink':'http://www.jobberman.com/',
  'footer.jobstreetseasia':'JobStreet (S.E. Asia)',
  'footer.jobstreetseasiaLink':'http://www.jobstreet.com/',
  'footer.jorahongkong':'Jora (Indonesia)',
  'footer.jorahongkongLink':'https://id.jora.com/',
  'footer.managerbrazil':'Manager (Brazil)',
  'footer.managerbrazilLink':'http://www.manager.com.br/',
  'footer.occmundialmexico':'OCC Mundial (Mexico)',
  'footer.dccmundialmexicoLink':'https://www.occ.com.mx/',
  'footer.seamanjobsitephilippines':'Seaman Jobsite (Philippines)',
  'footer.seamanjobsitephilippinesLink':'http://www.seamanjobsite.com/',
  'footer.seekaustralia':'SEEK (Australia)',
  'footer.seekaustraliaLink':'http://www.seek.com.au/',
  'footer.workabroadphilippines':'Work Abroad (Philippines)',
  'footer.workabroadphilippinesLink':'http://www.workabroad.ph/',
  'footer.workana':'Workana',
  'footer.workanaLink':'https://www.workana.com/',
  'footer.zhaopinchina':'Zhaopin (China)',
  'footer.zhaopinchinaLink':'http://www.zhaopin.com/',

  'footer.facebookLink':'https://www.facebook.com/jobsDBIndonesia.FP/',
  'footer.googleplusLink':'https://plus.google.com/111611346438127922663/posts',
  'footer.twitterLink':'https://twitter.com/JobsDBIndonesia',
  'footer.bloggerLink':'https://id.jobsdb.com/id-id/career-recruitment-advice/',
  'footer.socialrssLink':'http://id.jobsdb.com/ID/en/Rss/RenderJobFunctionRssIndex'
};
