
export default {
  'footer.copyright': 'Copyright © 1998-{year}, jobsDB. ',
  'footer.rightReserved': 'All Rights Reserved.',
  'footer.siteMapLink': '/th/en/sitemap',
  'footer.siteMapLinkText': 'Site Map',
  'footer.termsLink': '/en-th/pages/terms/terms-conditions',
  'footer.termsLinkText': 'Terms & Conditions',
  'footer.privacyLink': '/en-th/pages/terms/privacy-policy',
  'footer.privacyLinkText': 'Privacy Statement',

  'footer.csemailtext': 'Email: ',
  'footer.csemail': 'CS@jobsDB.co.th',
  'footer.csemailLink': 'mailto:CS@jobsDB.co.th',
  'footer.cshotline':'(662)667 0824 and (662)667 0700 ',
  'footer.officehour':'(Mon - Fri, 8:30am - 5:30pm)',
  'footer.jobpostingenquiry':'Job Posting Enquiry:',

  'footer.jobseekers':'Job Seekers',
  'footer.browsejobs':'Browse Jobs',
  'footer.browsejobsLink': '/th/en/browse',
  'footer.postresumes':'Post Resumes',
  'footer.postresumesLink': '/th/en/Resumes/ResumeIndex',
  'footer.jobalerts':'Job Alerts',
  'footer.jobalertsLink': '/th/en/JobAlert/JobAlertCreation',
  'footer.myjobsdb':'My jobsDB',
  'footer.myjobsdbLink': '/th/en/MyJobsDB',

  'footer.employers':'Employers',
  'footer.postajob':'Post a Job',
  'footer.postajobLink':'/th/en/Home/EmployerIndex',
  'footer.searchcandidates':'Search Candidates',
  'footer.searchcandidatesLink':'/en-th/cms/employer/product-services/talent-search/',
  'footer.advertisewithus':'Advertise with Us',
  'footer.advertisewithusLink':'/en-th/cms/employer/product-and-services/',

  'footer.aboutus':'About Us',
  'footer.aboutjobsdb':'About jobsDB',
  'footer.aboutjobsdbLink':'/en-th/pages/aboutus',
  'footer.faq':'FAQ',
  'footer.faqLink':'/th/en/StaticContentFullContainer/AboutUS/faq/index.htm',
  'footer.careenatjobsdb':'Career@jobsDB',
  'footer.careenatjobsdbLink':'/TH/en/Search/FindJobs?PN=JobListing&Companies=%22jobsDB%22',
  'footer.contactus':'Contact Us',
  'footer.contactusLink':'/en-th/pages/regional-coverage',

  'footer.tools':'Tools',
  'footer.mobileversion':'Mobile Version',
  'footer.mobileversionLink':'/en-th',
  'footer.rss':'RSS',
  'footer.rssLink':'/th/en/Rss/RenderJobFunctionRssIndex',

  'footer.internationalpartners':'International Partners',
  'footer.babajobindia':'BabaJob (India)',
  'footer.babajobindiaLink':'http://www.babajob.com/',
  'footer.bdjobsbandladesh':'Bdjobs (Bangladesh)',
  'footer.bdjobsbandladeshLink':'http://www.bdjobs.com/',
  'footer.brightermondayeastafrica':'Brighter Monday (East Africa)',
  'footer.brightermondayeastafricaLink':'http://www.brightermonday.com/',
  'footer.cathobrazil':'Catho (Brazil)',
  'footer.cathobrazilLink':'http://www.catho.com.br/',
  'footer.jobbermanwestafrica':'Jobberman (West Africa)',
  'footer.jobbermanwestafricaLink':'http://www.jobberman.com/',
  'footer.jobstreetseasia':'JobStreet (S.E. Asia)',
  'footer.jobstreetseasiaLink':'http://www.jobstreet.com/',
  'footer.jorahongkong':'Jora (Thailand)',
  'footer.jorahongkongLink':'https://th.jora.com/',
  'footer.managerbrazil':'Manager (Brazil)',
  'footer.managerbrazilLink':'http://www.manager.com.br/',
  'footer.occmundialmexico':'OCC Mundial (Mexico)',
  'footer.dccmundialmexicoLink':'https://www.occ.com.mx/',
  'footer.seamanjobsitephilippines':'Seaman Jobsite (Philippines)',
  'footer.seamanjobsitephilippinesLink':'http://www.seamanjobsite.com/',
  'footer.seekaustralia':'SEEK (Australia)',
  'footer.seekaustraliaLink':'http://www.seek.com.au/',
  'footer.workabroadphilippines':'Work Abroad (Philippines)',
  'footer.workabroadphilippinesLink':'http://www.workabroad.ph/',
  'footer.workana':'Workana',
  'footer.workanaLink':'https://www.workana.com/',
  'footer.zhaopinchina':'Zhaopin (China)',
  'footer.zhaopinchinaLink':'http://www.zhaopin.com/',

  'footer.facebookLink':'https://www.facebook.com/JobsDBThailandFan',
  'footer.googleplusLink':'https://plus.google.com/109178512494210043142/posts',
  'footer.twitterLink':'https://twitter.com/jobsdbth',
  'footer.youtubeLink':'http://www.youtube.com/JobsdbThai',
  'footer.bloggerLink':'http://jobsdbthailand.blogspot.com/',
  'footer.socialrssLink':'http://th.jobsdb.com/TH/EN/Rss/RenderJobFunctionRssIndex',
  'footer.truehitsLink':'http://datawarehouse.dbd.go.th/bdw/search/search1.html',
  'footer.truehitsImgLink':'https://th.content.jobsdbcdn.com/Content/v327/Images/shared/v8revamp/dbd_registered.png'

};
