
export default {
  'footer.copyright': 'Hak Cipta© 1998-{year}, jobsDB.',
  'footer.rightReserved': 'Semua Hak Dilindungi.',
  'footer.siteMapLink': '/id/id/sitemap',
  'footer.siteMapLinkText': 'Sitemap',
  'footer.termsLink': '/id-id/pages/terms/terms-conditions',
  'footer.termsLinkText': 'Syarat dan ketentuan',
  'footer.privacyLink': '/id-id/pages/terms/privacy-policy',

  'footer.privacyLinkText': 'Pernyataan Privasi',

  'footer.csemailtext': 'Email: ',
  'footer.csemail': 'CS@jobsDB.co.id',
  'footer.csemailLink': 'mailto:CS@jobsDB.co.id',
  'footer.cshotline':'Telp: +62 21 3002 8899 ',
  'footer.csFax':'Fax: +62 21 3002 8888 / +62 21 5795 7733',
  'footer.officehour':'(Mon - Fri, 8:00am - 5:00pm)',
  'footer.jobpostingenquiry':'Informasi Pemasangan Iklan:',

  'footer.jobseekers':'Pencari Kerja',
  'footer.browsejobs':'Daftar Pekerjaan',
  'footer.browsejobsLink': '/id/id/browse',
  'footer.postresumes':'Daftarkan CV',
  'footer.postresumesLink': '/id/id/Resumes/ResumeIndex',
  'footer.jobalerts':'Job Alerts',
  'footer.jobalertsLink': '/id/id/JobAlert/JobAlertCreation',
  'footer.myjobsdb':'My jobsDB',
  'footer.myjobsdbLink': '/id/id/MyJobsDB',


  'footer.employers':'Perusahaan',
  'footer.postajob':'Tayangkan Iklan',
  'footer.postajobLink':'/id/id/Home/EmployerIndex',
  'footer.searchcandidates':'Cari Kandidat',
  'footer.searchcandidatesLink':'/id/id/StaticContentFullContainer/EM/FindTalent.htm',
  'footer.advertisewithus':'Beriklan Bersama Kami',
  'footer.advertisewithusLink':'/id/id/StaticContent/AboutUs/Products.htm',

  'footer.aboutus':'Tentang Kam',
  'footer.aboutjobsdb':'Tentang jobsDB',
  'footer.aboutjobsdbLink':'/id-id/pages/aboutus',
  'footer.faq':'FAQ',
  'footer.faqLink':'/id/id/StaticContentFullContainer/AboutUS/faq/index.htm',
  'footer.careenatjobsdb':'Karir@jobsDB',
  'footer.careenatjobsdbLink':'/id/id/Search/FindJobs?JSRV=1&AccNums=1&SubAccount=14',
  'footer.contactus':'Hubungi Kami',
  'footer.contactusLink':'/id-id/pages/regional-coverage',

  'footer.tools':'Tools',
  'footer.mobileversion':'Versi Mobile',
  'footer.mobileversionLink':'/id-id',
  'footer.rss':'RSS',
  'footer.rssLink':'/id/id/Rss/RenderJobFunctionRssIndex',

  'footer.internationalpartners':'Partner Internasional',
  'footer.babajobindia':'BabaJob (India)',
  'footer.babajobindiaLink':'http://www.babajob.com/',
  'footer.bdjobsbandladesh':'Bdjobs (Bandladesh)',
  'footer.bdjobsbandladeshLink':'http://www.bdjobs.com/',
  'footer.brightermondayeastafrica':'Brighter Monday (East Africa)',
  'footer.brightermondayeastafricaLink':'http://www.brightermonday.com/',
  'footer.cathobrazil':'Catho (Brazil)',
  'footer.cathobrazilLink':'http://www.catho.com.br/',
  'footer.jobbermanwestafrica':'Jobberman (West Africa)',
  'footer.jobbermanwestafricaLink':'http://www.jobberman.com/',
  'footer.jobstreetseasia':'JobStreet (S.E. Asia)',
  'footer.jobstreetseasiaLink':'http://www.jobstreet.com/',
  'footer.jorahongkong':'Jora (Hong Kong)',
  'footer.jorahongkongLink':'https://hk.jora.com/',
  'footer.managerbrazil':'Manager (Brazil)',
  'footer.managerbrazilLink':'http://www.manager.com.br/',
  'footer.occmundialmexico':'OCC Mundial (Mexico)',
  'footer.dccmundialmexicoLink':'https://www.occ.com.mx/',
  'footer.seamanjobsitephilippines':'Seaman Jobsite (Philippines)',
  'footer.seamanjobsitephilippinesLink':'http://www.seamanjobsite.com/',
  'footer.seekaustralia':'SEEK (Australia)',
  'footer.seekaustraliaLink':'http://www.seek.com.au/',
  'footer.workabroadphilippines':'Work Abroad (Philippines)',
  'footer.workabroadphilippinesLink':'http://www.workabroad.ph/',
  'footer.workana':'Workana',
  'footer.workanaLink':'https://www.workana.com/',
  'footer.zhaopinchina':'Zhaopin (China)',
  'footer.zhaopinchinaLink':'http://www.zhaopin.com/',

  'footer.facebookLink':'https://www.facebook.com/jobsDBIndonesia.FP/',
  'footer.googleplusLink':'https://plus.google.com/111611346438127922663/posts',
  'footer.twitterLink':'https://twitter.com/JobsDBIndonesia',
  'footer.bloggerLink':'http://jobsdb-indonesia.blogspot.com/',
  'footer.rssLink':'http://id.jobsdb.com/ID/en/Rss/RenderJobFunctionRssIndex'
 };
