
export default {
  'footer.copyright': 'สงวนลิขสิทธิ์ 1998-{year} โดย บริษัท จัดหางาน จ๊อบส์ ดีบี (ประเทศไทย) จำกัด',
  'footer.rightReserved': '',
  'footer.siteMapLink': '/th/th/sitemap',
  'footer.siteMapLinkText': 'แผนที่เว็บไซต์',
  'footer.termsLink': '/th-th/pages/terms/terms-conditions',
  'footer.termsLinkText': 'ข้อกำหนดและเงื่อนไข',
  'footer.privacyLink': '/th-th/pages/terms/privacy-policy',
  'footer.privacyLinkText': 'คำชี้แจงสิทธิส่วนบุคคล',

  'footer.csemailtext': 'อีเมล: ',
  'footer.csemail': 'CS@jobsDB.co.th',
  'footer.csemailLink': 'mailto:CS@jobsDB.co.th',
  'footer.cshotline':'(662)667 0824 และ (662)667 0700 ',
  'footer.officehour':'(เวลาทำการ จันทร์ – ศุกร์ 8.30 น. – 17.30 น.)',
  'footer.jobpostingenquiry':'สอบถามข้อมูลในการลงประกาศงาน:',

  'footer.jobseekers':'ผู้หางาน',
  'footer.browsejobs':'หางาน',
  'footer.browsejobsLink': '/th/th/browse',
  'footer.postresumes':'สร้างเรซูเม่',
  'footer.postresumesLink': '/th/th/Resumes/ResumeIndex',
  'footer.jobalerts':'อีเมลแจ้งงานด่วน',
  'footer.jobalertsLink': '/th/th/JobAlert/JobAlertCreation',
  'footer.myjobsdb':'My jobsDB',
  'footer.myjobsdbLink': '/th/th/MyJobsDB',


  'footer.employers':'ผู้ประกอบการ',
  'footer.postajob':'ลงประกาศงาน',
  'footer.postajobLink':'/th/th/Home/EmployerIndex',
  'footer.searchcandidates':'ค้นหาผู้สมัครงาน',
  'footer.searchcandidatesLink':'/th-th/cms/employer/product-services/talent-search/',
  'footer.advertisewithus':'ลงโฆษณา',
  'footer.advertisewithusLink':'/th-th/cms/employer/product-and-services/',

  'footer.aboutus':'เกี่ยวกับเรา',
  'footer.aboutjobsdb':'เกี่ยวกับจ๊อบส์ดีบี',
  'footer.aboutjobsdbLink':'/th-th/pages/aboutus',
  'footer.faq':'คำถามที่พบบ่อย',
  'footer.faqLink':'/th/th/StaticContentFullContainer/AboutUS/faq/index.htm',
  'footer.careenatjobsdb':'ร่วมงานกับจ๊อบส์ดีบี',
  'footer.careenatjobsdbLink':'/TH/th/Search/FindJobs?PN=JobListing&Companies=%22jobsDB%22',
  'footer.contactus':'ติดต่อเรา',
  'footer.contactusLink':'/th-th/pages/regional-coverage',

  'footer.tools':'เครื่องมือ',
  'footer.mobileversion':'หางานผ่านมือถือ',
  'footer.mobileversionLink':'/th-th',
  'footer.rss':'RSS',
  'footer.rssLink':'/th/th/Rss/RenderJobFunctionRssIndex',

  'footer.internationalpartners':'พันธมิตรต่างชาติ',
  'footer.babajobindia':'BabaJob (India)',
  'footer.babajobindiaLink':'http://www.babajob.com/',
  'footer.bdjobsbandladesh':'Bdjobs (Bangladesh)',
  'footer.bdjobsbandladeshLink':'http://www.bdjobs.com/',
  'footer.brightermondayeastafrica':'Brighter Monday (East Africa)',
  'footer.brightermondayeastafricaLink':'http://www.brightermonday.com/',
  'footer.cathobrazil':'Catho (Brazil)',
  'footer.cathobrazilLink':'http://www.catho.com.br/',
  'footer.jobbermanwestafrica':'Jobberman (West Africa)',
  'footer.jobbermanwestafricaLink':'http://www.jobberman.com/',
  'footer.jobstreetseasia':'JobStreet (S.E. Asia)',
  'footer.jobstreetseasiaLink':'http://www.jobstreet.com/',
  'footer.jorahongkong':'Jora (Thailand)',
  'footer.jorahongkongLink':'https://th.jora.com/',
  'footer.managerbrazil':'Manager (Brazil)',
  'footer.managerbrazilLink':'http://www.manager.com.br/',
  'footer.occmundialmexico':'OCC Mundial (Mexico)',
  'footer.dccmundialmexicoLink':'https://www.occ.com.mx/',
  'footer.seamanjobsitephilippines':'Seaman Jobsite (Philippines)',
  'footer.seamanjobsitephilippinesLink':'http://www.seamanjobsite.com/',
  'footer.seekaustralia':'SEEK (Australia)',
  'footer.seekaustraliaLink':'http://www.seek.com.au/',
  'footer.workabroadphilippines':'Work Abroad (Philippines)',
  'footer.workabroadphilippinesLink':'http://www.workabroad.ph/',
  'footer.workana':'Workana',
  'footer.workanaLink':'https://www.workana.com/',
  'footer.zhaopinchina':'Zhaopin (China)',
  'footer.zhaopinchinaLink':'http://www.zhaopin.com/',

  'footer.facebookLink':'https://www.facebook.com/JobsDBThailandFan',
  'footer.googleplusLink':'https://plus.google.com/109178512494210043142/posts',
  'footer.twitterLink':'https://twitter.com/jobsdbth',
  'footer.youtubeLink':'http://www.youtube.com/JobsdbThai',
  'footer.bloggerLink':'http://jobsdbthailand.blogspot.com/',
  'footer.socialrssLink':'http://th.jobsdb.com/TH/EN/Rss/RenderJobFunctionRssIndex',
  'footer.datawarehouseLink':'http://datawarehouse.dbd.go.th/bdw/search/search1.html',
  'footer.datawarehouseImgLink':'https://th.content.jobsdbcdn.com/Content/v327/Images/shared/v8revamp/dbd_registered.png'

  };
