import React from 'react';
import Button from './Button';

export const symbols = {
  'Button/Call To Action/Standard/Standard': <Button color="callToAction">Button</Button>,
  'Button/Call To Action/Standard/Compact': <Button color="callToAction" compact>Button</Button>,
  'Button/Call To Action/Inverse/Standard': <Button color="callToAction" inverse>Button</Button>,
  'Button/Call To Action/Inverse/Compacy': <Button color="callToAction" inverse compact>Button</Button>,
  'Button/Call To Action/Ghost/Standard': <Button color="callToAction" ghost>Button</Button>,
  'Button/Call To Action/Ghost/Compact': <Button color="callToAction" ghost compact>Button</Button>,
  'Button/Hyperlink/Standard/Standard': <Button color="hyperlink">Button</Button>,
  'Button/Hyperlink/Standard/Compact': <Button color="hyperlink" compact>Button</Button>,
  'Button/Hyperlink/Inverse/Standard': <Button color="hyperlink" inverse>Button</Button>,
  'Button/Hyperlink/Inverse/Compact': <Button color="hyperlink" inverse compact>Button</Button>,
  'Button/Hyperlink/Ghost/Standard': <Button color="hyperlink" ghost>Button</Button>,
  'Button/Hyperlink/Ghost/Compact': <Button color="hyperlink" ghost compact>Button</Button>,
  'Button/Completion/Standard/Standard': <Button color="completion">Button</Button>,
  'Button/Completion/Standard/Compact': <Button color="completion" compact>Button</Button>,
  'Button/Completion/Inverse/Standard': <Button inverse color="completion">Button</Button>,
  'Button/Completion/Inverse/Compact': <Button inverse color="completion" compact>Button</Button>,
  'Button/Completion/Ghost/Standard': <Button ghost color="completion">Button</Button>,
  'Button/Completion/Ghost/Compact': <Button ghost color="completion" compact>Button</Button>,
  'Button/Alert/Standard/Standard': <Button color="alert">Button</Button>,
  'Button/Alert/Standard/Compact': <Button color="alert" compact>Button</Button>,
  'Button/Alert/Inverse/Standard': <Button color="alert" inverse>Button</Button>,
  'Button/Alert/Inverse/Compact': <Button color="alert" inverse compact>Button</Button>,
  'Button/Alert/Ghost/Standard': <Button color="alert" ghost>Button</Button>,
  'Button/Alert/Ghost/Compact': <Button color="alert" ghost compact>Button</Button>,
  'Button/Highlight/Standard/Standard': <Button color="highlight">Highlight</Button>,
  'Button/Highlight/Standard/Compact': <Button color="highlight" compact>Highlight</Button>,
  'Button/Highlight/Inverse/Standard': <Button color="highlight" inverse>Highlight</Button>,
  'Button/Highlight/Inverse/Compact': <Button color="highlight" compact inverse>Highlight</Button>,
  'Button/Highlight/Ghost/Standard': <Button color="highlight" ghost>Highlight</Button>,
  'Button/Highlight/Ghost/Compact': <Button color="highlight" ghost compact>Highlight</Button>,
  'Button/Transparent/Standard': <Button color="transparent">Button</Button>,
  'Button/Transparent/Compact': <Button color="transparent" compact>Button</Button>
};
