const baseUrl = 'https://jobstreet.com.my';
const baseUrlWithLanguage = `${baseUrl}/en`;

export default {
  'footer.copyright': 'Copyright © {year} JobStreet.com',
  'footer.link': 'https://www.jobstreet.com',
  'footer.linkText': 'JobStreet International',
  'footer.siteMapLink': `${baseUrl}/sitemap.htm`,
  'footer.siteMapLinkText': 'Site Map',
  'footer.aboutLink': `${baseUrlWithLanguage}/about-us/`,
  'footer.aboutLinkText': 'About Us',
  'footer.profilesLink': `${baseUrl}/career/JobStreet.htm`,
  'footer.profilesLinkText': 'Work With Us',
  'footer.termsLink': `${baseUrlWithLanguage}/about-us/terms-of-use/`,
  'footer.termsLinkText': 'Term of Use',
  'footer.privacyLink': `${baseUrlWithLanguage}/about-us/privacy-policy/`,
  'footer.privacyLinkText': 'Privacy Policy',
  'footer.safeLink': `${baseUrlWithLanguage}/about-us/safe-job-search-guide/`,
  'footer.safeLinkText': 'Safe Job Search Guide',
  'footer.helpLink': `${baseUrlWithLanguage}/user/`,
  'footer.helpLinkText': 'Help',
  'footer.feedbackLink': 'https://myjobstreet.jobstreet.com.my/home/feedback.php?site=my&sub=feedback',
  'footer.feedbackLinkText': 'Send Feedback',
  'header.homeLink': `${baseUrl}`,
  'header.homeTitle': 'Leading Job Site in Malaysia - Find Jobs in Malaysia',
  'header.homeText': 'Home',
  'header.employerLink': `${baseUrlWithLanguage}/cms/employer`,
  'header.employerTitle': 'Post a Job Ad: +603-2176 0333',
  'header.employerText': 'Employer',
  'header.searchLink': 'https://srp-alpha.jobstreet.com',
  'header.searchTitle': 'Search Jobs @ Job Search JobStreet.com Malaysia',
  'header.searchText': 'Search Jobs',
  'header.myJobStreetLink': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my',
  'header.myJobStreetLoggedInLink': 'https://myjobstreet.jobstreet.com.my/resume/preview-resume.php?',
  'header.myJobStreetTitle': 'Post Resume, Signup for Job Alert & Apply for Jobs @ MyJobStreet Malaysia',
  'header.myJobStreetText': 'MyJobStreet',
  'header.companyProfilesLink': `${baseUrlWithLanguage}/companies`,
  'header.companyProfilesTitle': 'JobStreet.com Malaysia - Company Profiles',
  'header.companyProfilesText': 'Company Profiles',
  'header.careerInsightsLink': `${baseUrlWithLanguage}/career-insights`,
  'header.careerInsightsTitle': 'JobStreet.com Malaysia - Career Insights',
  'header.careerInsightsText': 'Career Insights',
  'header.jobStreetEducationLink': 'https://www.jobstreeteducation.com.my/',
  'header.jobStreetEducationTitle': '',
  'header.jobStreetEducationText': 'Education',
  'header.moreTitle': '',
  'header.moreText': 'More',
  'header.overseasJobsLink': 'https://www.jobstreet.com.my/en/job-search/browse/find-overseas-jobs',
  'header.overseasJobsTitle': '',
  'header.overseasJobsText': 'Overseas Jobs',
  'header.freshGradJobsLink': 'https://www.jobstreet.com.my/en/job-search/campus/job-vacancy.php',
  'header.freshGradJobsTitle': '',
  'header.freshGradJobsText': 'Fresh Grad Jobs',
  'header.classifiedJobsLink': 'https://www.jobstreet.com.my/en/job-search/classified-ads.php',
  'header.classifiedJobsTitle': '',
  'header.classifiedJobsText': 'Classified Jobs',
  'header.loginLink': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my&language_code=3',
  'header.loginTitle': '',
  'header.loginText': 'Log In',
  'header.signUpLink': 'https://myjobstreet.jobstreet.com.my/registration/simple-signup.php?site=my&language_code=3',
  'header.signUpTitle': '',
  'header.signUpText': 'Sign Up',
  'header.logoutLink': 'https://myjobstreet.jobstreet.com.my/home/logout.php?',
  'header.logoutTitle': '',
  'header.logoutText': 'Logout',
  'header.helpLink': 'https://myjobstreet.jobstreet.com.my/home/help.php?',
  'header.helpTitle': '',
  'header.helpText': 'Help',
  'header.myAccountLink': 'https://myjobstreet.jobstreet.com.my/registration/update-account.php?',
  'header.myAccountTitle': '',
  'header.myAccountText': 'My Account'
};
