const baseUrl = 'https://jobstreet.com.my';
const baseUrlWithLanguage = `${baseUrl}/en`;

export default {
  'footer.copyright': 'Copyright © {year} JobStreet.com',
  'footer.link': 'https://www.jobstreet.com',
  'footer.linkText': 'JobStreet International',
  'footer.siteMapLink': `${baseUrl}/sitemap.htm`,
  'footer.siteMapLinkText': 'Site Map',
  'footer.aboutLink': `${baseUrlWithLanguage}/about-us/`,
  'footer.aboutLinkText': 'About Us',
  'footer.profilesLink': `${baseUrl}/career/JobStreet.htm`,
  'footer.profilesLinkText': 'Work With Us',
  'footer.termsLink': `${baseUrlWithLanguage}/about-us/terms-of-use/`,
  'footer.termsLinkText': 'Term of Use',
  'footer.privacyLink': `${baseUrlWithLanguage}/about-us/privacy-policy/`,
  'footer.privacyLinkText': 'Privacy Policy',
  'footer.safeLink': `${baseUrlWithLanguage}/about-us/safe-job-search-guide/`,
  'footer.safeLinkText': 'Safe Job Search Guide',
  'footer.helpLink': `${baseUrlWithLanguage}/user/`,
  'footer.helpLinkText': 'Help',
  'footer.feedbackLink': 'https://myjobstreet.jobstreet.com.my/home/feedback.php?site=my&sub=feedback',
  'footer.feedbackLinkText': 'Send Feedback',
  'header.homeLink': `${baseUrl}`,
  'header.homeTitle': 'Leading Job Site in Malaysia - Find Jobs in Malaysia',
  'header.searchLink': 'https://srp-alpha.jobstreet.com',
  'header.searchTitle': 'Search Jobs @ Job Search JobStreet.com Malaysia',
  'header.myJobStreetLink': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my',
  'header.myJobStreetTitle': 'Post Resume, Signup for Job Alert & Apply for Jobs @ MyJobStreet Malaysia',
  'header.profilesLink': `${baseUrlWithLanguage}/companies`,
  'header.profilesTitle': 'JobStreet.com Malaysia - Company Profiles',
  'header.careerInsightsLink': `${baseUrlWithLanguage}/career-insights`,
  'header.careerInsightsTitle': 'JobStreet.com Malaysia - Career Insights',
  'header.jobStreetEducationLink': 'https://www.jobstreeteducation.com.my/',
  'header.jobStretEducationTitle': '',
  'header.moreTitle': '',
  'header.overseasJobsLink': 'https://www.jobstreet.com.my/en/job-search/browse/find-overseas-jobs',
  'header.overseasJobsTitle': '',
  'header.freshGradJobsLink': 'https://www.jobstreet.com.my/en/job-search/campus/job-vacancy.php',
  'header.freshGradJobsTitle': '',
  'header.classifiedJobsLink': 'https://www.jobstreet.com.my/en/job-search/classified-ads.php',
  'header.classifiedJobsTitle': '',
  'header.loginLink': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my&language_code=3',
  'header.loginTitle': '',
  'header.signUpLink': 'https://myjobstreet.jobstreet.com.my/registration/simple-signup.php?site=my&language_code=3',
  'header.signUpTitle': '',
  'header.logoutLink': '',
  'header.logoutTitle': '',
  'header.logoutText': '',
  'header.helpLink': '',
  'header.helpTitle': '',
  'header.helpText': '',
  'header.accountLink': '',
  'header.accountTitle': '',
  'header.accountText': ''
};
