const baseUrl = 'https://jobstreet.com.sg';
const baseUrlWithLanguage = `${baseUrl}/en`;

export default {
  'footer.copyright': 'Copyright © {year} JobStreet.com',
  'footer.link': 'https://www.jobstreet.com',
  'footer.linkText': 'JobStreet International',
  'footer.siteMapLink': `${baseUrl}/sitemap.htm`,
  'footer.siteMapLinkText': 'Site Map',
  'footer.aboutLink': `${baseUrlWithLanguage}/about-us/`,
  'footer.aboutLinkText': 'About Us',
  'footer.profilesLink': `${baseUrl}/career/JobStreet.htm`,
  'footer.profilesLinkText': 'Work With Us',
  'footer.termsLink': `${baseUrlWithLanguage}/about-us/terms-of-use/`,
  'footer.termsLinkText': 'Term of Use',
  'footer.privacyLink': `${baseUrlWithLanguage}/about-us/privacy-policy/`,
  'footer.privacyLinkText': 'Privacy Policy',
  'footer.safeLink': `${baseUrlWithLanguage}/about-us/safe-job-search-guide/`,
  'footer.safeLinkText': 'Safe Job Search Guide',
  'footer.helpLink': `${baseUrlWithLanguage}/user/`,
  'footer.helpLinkText': 'Help',
  'footer.feedbackLink':
    'https://myjobstreet.jobstreet.com.sg/home/feedback.php?site=sg&sub=feedback',
  'footer.feedbackLinkText': 'Send Feedback',
  'header.homeTitle': 'Home',
  'header.homeUrl': baseUrl,
  'header.myJobStreetTitle': 'MyJobStreet',
  'header.myJobStreetUrl': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my',
  'header.companyProfilesTitle': 'Company Profiles',
  'header.companyProfilesUrl': `${baseUrlWithLanguage}/companies/`,
  'header.careerInsightsTitle': 'Career Insights',
  'header.careerInsightsUrl': `${baseUrlWithLanguage}/career-insights`,
  'header.educationTitle': 'Education',
  'header.educationUrl': `${baseUrlWithLanguage}/career-insights`,
  'header.myAccountTitle': 'My Account',
  'header.myAccountUrl': 'https://myjobstreet.jobstreet.com.my/resume/preview-resume.php?',
  'header.employerSiteTitle': 'Employer Site',
  'header.employerLinkPrefix': 'Looking to hire? Check out our ',
  'header.employerSiteUrl': '${baseUrlWithLanguage}/cms/employer',
  'header.overseasJobsTitle': 'Overseas Jobs',
  'header.overseasJobsUrl': `${baseUrlWithLanguage}/job-search/browse/find-overseas-jobs`,
  'header.freshGradJobsTitle': 'Fresh Grad Jobs',
  'header.freshGradJobsUrl': `${baseUrlWithLanguage}/job-search/campus/job-vacancy.php`,
  'header.classifiedJobsTitle': 'Classified Jobs',
  'header.classifiedJobsUrl': `${baseUrlWithLanguage}/job-search/classified-ads.php`,
  'menu.jobSeekerHeader': 'JOB SEEKER',
  'menu.settingsHeader': 'SETTINGS',
  'menu.more': 'More',
  'menu.moreHeader': 'MORE',
  'menu.countryAndLanguage': 'Country & Language',
  'menu.backToMenu': 'Back to Menu'
};
