const baseUrl = 'https://jobstreet.co.id';
const baseUrlWithLanguage = `${baseUrl}/id`;

export default {
  'footer.copyright': 'Hak Cipta © {year} JobStreet.com',
  'footer.link': 'https://www.jobstreet.com',
  'footer.linkText': 'JobStreet Internasional',
  'footer.siteMapLink': `${baseUrl}/sitemap.htm`,
  'footer.siteMapLinkText': 'Site Map',
  'footer.aboutLink': `${baseUrlWithLanguage}/about-us/`,
  'footer.aboutLinkText': 'Tentang Kami',
  'footer.profilesLink': `${baseUrl}/en/companies/778589-jobstreet`,
  'footer.profilesLinkText': 'Berkarier bersama Kami',
  'footer.termsLink': `${baseUrlWithLanguage}/about-us/ketentuan-penggunaan/`,
  'footer.termsLinkText': 'Ketentuan Penggunaan',
  'footer.privacyLink': `${baseUrlWithLanguage}/about-us/kebijakan-privasi/`,
  'footer.privacyLinkText': 'Kebijakan Kerahasiaan',
  'footer.safeLink': `${baseUrlWithLanguage}/about-us/panduan-dan-tips-mencari-kerja-online-secara-aman/`,
  'footer.safeLinkText': 'Panduan Mencari Kerja Secara Aman',
  'footer.helpLink': `${baseUrlWithLanguage}/user/`,
  'footer.helpLinkText': 'Bantuan',
  'footer.feedbackLink':
    'https://myjobstreet.jobstreet.co.id/home/feedback.php?site=id&sub=feedback',
  'footer.feedbackLinkText': 'Kirim Saran',
  'header.homeTitle': 'Home',
  'header.homeUrl': baseUrl,
  'header.myJobStreetTitle': 'MyJobStreet',
  'header.myJobStreetUrl': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my',
  'header.companyProfilesTitle': 'Company Profiles',
  'header.companyProfilesUrl': `${baseUrlWithLanguage}/companies/`,
  'header.careerInsightsTitle': 'Career Insights',
  'header.careerInsightsUrl': `${baseUrlWithLanguage}/career-insights`,
  'header.educationTitle': 'Education',
  'header.educationUrl': `${baseUrlWithLanguage}/career-insights`,
  'header.myAccountTitle': 'My Account',
  'header.myAccountUrl': 'https://myjobstreet.jobstreet.com.my/resume/preview-resume.php?',
  'header.employerSiteTitle': 'Employer Site',
  'header.employerLinkPrefix': 'Looking to hire? Check out our ',
  'header.employerSiteUrl': '${baseUrlWithLanguage}/cms/employer',
  'header.overseasJobsTitle': 'Overseas Jobs',
  'header.overseasJobsUrl': `${baseUrlWithLanguage}/job-search/browse/find-overseas-jobs`,
  'header.freshGradJobsTitle': 'Fresh Grad Jobs',
  'header.freshGradJobsUrl': `${baseUrlWithLanguage}/job-search/campus/job-vacancy.php`,
  'header.classifiedJobsTitle': 'Classified Jobs',
  'header.classifiedJobsUrl': `${baseUrlWithLanguage}/job-search/classified-ads.php`,
  'menu.jobSeekerHeader': 'JOB SEEKER',
  'menu.settingsHeader': 'SETTINGS',
  'menu.more': 'More',
  'menu.moreHeader': 'MORE',
  'menu.countryAndLanguage': 'Country & Language',
  'menu.backToMenu': 'Back to Menu'
};
