const baseUrl = 'https://jobstreet.vn';
const baseUrlWithLanguage = `${baseUrl}/vi`;

export default {
  'footer.copyright': 'Copyright © {year} JobStreet.com',
  'footer.link': 'https://www.jobstreet.com',
  'footer.linkText': 'JobStreet Quốc Tế',
  'footer.siteMapLink': `${baseUrl}/sitemap.htm`,
  'footer.siteMapLinkText': 'Site Map',
  'footer.aboutLink': `${baseUrlWithLanguage}/about-us/`,
  'footer.aboutLinkText': 'Về JobStreet',
  'footer.profilesLink': `${baseUrlWithLanguage}/companies/762582-jobstreet-company-limited-vn`,
  'footer.profilesLinkText': 'Cơ Hội Nghề Nghiệp',
  'footer.termsLink': `${baseUrlWithLanguage}/about-us/dieu-khoan-su-dung/`,
  'footer.termsLinkText': 'Điều Khoản Sử Dụng',
  'footer.privacyLink': `${baseUrlWithLanguage}/about-us/chinh-sach-bao-mat/`,
  'footer.privacyLinkText': 'Chính Sách Bảo Mật',
  'footer.safeLink': `${baseUrlWithLanguage}/about-us/huong-dan-va-bi-quyet-tim-viec-truc-tuyen-an-toan/`,
  'footer.safeLinkText': 'Mẹo Tìm Việc An Toàn',
  'footer.helpLink': `${baseUrlWithLanguage}/user/`,
  'footer.helpLinkText': 'Trợ Giúp',
  'footer.feedbackLink':
    'https://myjobstreet.jobstreet.vn/home/feedback.php?site=vn&sub=feedback',
  'footer.feedbackLinkText': 'Gửi Phản Hồi',
  'header.homeTitle': 'Home',
  'header.homeUrl': baseUrl,
  'header.myJobStreetTitle': 'MyJobStreet',
  'header.myJobStreetUrl': 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my',
  'header.companyProfilesTitle': 'Company Profiles',
  'header.companyProfilesUrl': `${baseUrlWithLanguage}/companies/`,
  'header.careerInsightsTitle': 'Career Insights',
  'header.careerInsightsUrl': `${baseUrlWithLanguage}/career-insights`,
  'header.educationTitle': 'Education',
  'header.educationUrl': `${baseUrlWithLanguage}/career-insights`,
  'header.myAccountTitle': 'My Account',
  'header.myAccountUrl': 'https://myjobstreet.jobstreet.com.my/resume/preview-resume.php?',
  'header.employerSiteTitle': 'Employer Site',
  'header.employerLinkPrefix': 'Looking to hire? Check out our ',
  'header.employerSiteUrl': '${baseUrlWithLanguage}/cms/employer',
  'header.overseasJobsTitle': 'Overseas Jobs',
  'header.overseasJobsUrl': `${baseUrlWithLanguage}/job-search/browse/find-overseas-jobs`,
  'header.freshGradJobsTitle': 'Fresh Grad Jobs',
  'header.freshGradJobsUrl': `${baseUrlWithLanguage}/job-search/campus/job-vacancy.php`,
  'header.classifiedJobsTitle': 'Classified Jobs',
  'header.classifiedJobsUrl': `${baseUrlWithLanguage}/job-search/classified-ads.php`,
  'menu.jobSeekerHeader': 'JOB SEEKER',
  'menu.settingsHeader': 'SETTINGS',
  'menu.more': 'More',
  'menu.moreHeader': 'MORE',
  'menu.countryAndLanguage': 'Country & Language',
  'menu.backToMenu': 'Back to Menu'
};
