#! /bin/bash
red=`tput setab 1`
reset=`tput sgr0`
if grep -q '//npmregistryinternal.seekinfra.com:4873/:_authToken=' ~/.npmrc
then
  exit 0
else
  echo "${red}ERR!${reset} Auth is required for publishing"
  echo "${red}ERR!${reset} You need to authorize this machine using 'npm adduser --registry http://npmregistryinternal.seekinfra.com:4873'${reset}"
  exit 1
fi
